#!/bin/bash

# set (and redraw) background image with Feh
feh --bg-scale ~/utils/wallpaper/current &

# start trayer
trayer --edge top --align right --SetDockType true --SetPartialStrut true  --expand true --width 11 --transparent true --tint 0x000000 --alpha 0 --height 17 &

# network manager applet
if [ -x /usr/bin/nm-applet ] ; then
   nm-applet --sm-disable &
fi
