#!/bin/bash

# for some reason this is required since ubuntu 14.04. Feh needs to be installed
# set (and redraw) background image with Feh
feh --bg-scale ~/utils/wallpaper/current &

# custom applets so we dont need the stupid indicator thing
# dbus-launch nm-applet &
# dbus-launch gnome-sound-applet &
# dbus-launch xfce4-power-manager &
