#!/bin/bash

# set (and redraw) background image with Feh
feh --bg-scale ~/utils/wallpaper/current &

# start trayer
trayer --edge top --align right --SetDockType true --SetPartialStrut true  --expand true --width 6 --transparent true --tint 0x000000 --alpha 0 --height 17 &

# network manager applet
if [ -x /usr/bin/nm-applet ] ; then
   nm-applet --sm-disable &
fi

# lock the screen after 10 minutes
xautolock -time 10 -locker slock &

# set default cursor to left arrow head
xsetroot -cursor_name left_ptr