#!/bin/sh

userresources=$HOME/.Xresources
sysresources=/etc/X11/xinit/.Xresources

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

# set (and redraw) background image with Feh
feh --bg-scale ~/code/dotfiles/wallpaper/current &

# lock the screen after 10 minutes
xautolock -time 10 -locker i3lock &

# set keyboard map
setxkbmap gb &